# Generated by Django 5.2.12 on 2026-04-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitterprofile',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='babysitterprofile',
            name='number',
        ),
        migrations.RemoveField(
            model_name='babysitterprofile',
            name='pix_key',
        ),
        migrations.RemoveField(
            model_name='babysitterprofile',
            name='service_radius',
        ),
        migrations.RemoveField(
            model_name='babysitterprofile',
            name='street',
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='housing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='title',
            field=models.CharField(blank=True, default='Babá profissional', max_length=200),
        ),
        migrations.AlterField(
            model_name='babysitterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='babysitter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BabysitterActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.BooleanField(default=False)),
                ('educational_toys', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('social_skills', models.BooleanField(default=False)),
                ('arts', models.BooleanField(default=False)),
                ('cooking', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('crafts', models.BooleanField(default=False)),
                ('babysitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabysitterBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_orientation', models.TextField(blank=True, default='')),
                ('playtime', models.TextField(blank=True, default='')),
                ('flexibility', models.TextField(blank=True, default='')),
                ('parent_communication', models.TextField(blank=True, default='')),
                ('daily_routine', models.TextField(blank=True, default='')),
                ('situation_dilemma', models.TextField(blank=True, default='')),
                ('babysitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabysitterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('employer', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('age_ranges', models.JSONField(default=list)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BabysitterPersonalTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organized', models.IntegerField(default=3)),
                ('patient', models.IntegerField(default=3)),
                ('creative', models.IntegerField(default=3)),
                ('attentive', models.IntegerField(default=3)),
                ('playful', models.IntegerField(default=3)),
                ('bio_quote', models.TextField(blank=True, default='')),
                ('babysitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_traits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabysitterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BabysitterTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('completed', models.BooleanField(default=True)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabysitterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('overnight', models.BooleanField(default=False)),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('babysitter', 'day_of_week')},
            },
        ),
    ]
